### ISSUE TITLE
Display version of python

### ISSUE THREAD

**Issue by l50** [wunderhund/dotfiles#3]
If a version of python that comes from pyenv is being used, display the version number in the prompt.

**Comment by wunderhund** [comment]
Great idea, I will investigate how to do this!

**Comment by wunderhund** [comment]
Work in progress, the pyenv plugin for zsh is not as user-friendly as the git and virtualenv ones. https://github.com/wunderhund/dotfiles/pull/4

**Comment by wunderhund** [comment]
Merged #4, this issue is resolved.
